CREATE DATABASE assistenciadv;
USE assistenciadv;
CREATE TABLE agendamentos(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
telefone VARCHAR(20) NOT NULL,
aparelho VARCHAR(50) NOT NULL,
dat DATE NOT NULL,
descricao TEXT NOT NULL,
data_envio TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
